spring:
  profiles:
    include: aws

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  redis:
    host: 127.0.0.1
    port: 6379

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

