spring:
  profiles:
    include: aws

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  redis:
    host: localhost
    port: 6379

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

